name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Fetch submodules
        run: |
          git submodule update --init --recursive

      - name: Install dependencies
        run: sudo apt-get install -y make gcc g++

      - name: Build
        run: make build
